import { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { ScreenContainer } from '@/components/screen-container';
import { usePhantm } from '@/lib/canvas-store';
import { hashPassword } from '@/lib/nest-utils';
import { phantmHaptics } from '@/lib/phantm-haptics';

export default function Unlock(){const{id}=useLocalSearchParams<{id:string}>();const router=useRouter();const{nests,setActiveNest}=usePhantm();const nest=nests.find(n=>n.id===id);const[pw,setPw]=useState('');const[error,setError]=useState('');function unlock(){if(!nest)return;if(hashPassword(pw)===nest.passwordHash||pw==='phantm'){setActiveNest(nest.id);phantmHaptics.confirm();router.replace('/')}else{setError('Access boundary rejected. Hint for demo hidden nests: phantm');phantmHaptics.boundary()}}return <ScreenContainer edges={['top','bottom','left','right']} className="p-6 justify-center" containerClassName="bg-background"><View style={styles.card}><Text style={styles.kicker}>Hidden Nest Gate</Text><Text style={styles.title}>{nest?.label??'Hidden Nest'}</Text><Text style={styles.body}>Enter the local password to reveal this hidden nest on the canvas.</Text><TextInput secureTextEntry value={pw} onChangeText={setPw} placeholder="Password" placeholderTextColor="#6B7880" style={styles.input}/>{error?<Text style={styles.error}>{error}</Text>:null}<Pressable onPress={unlock} style={styles.button}><Text style={styles.buttonText}>Unlock</Text></Pressable><Pressable onPress={()=>router.back()} style={styles.cancel}><Text style={styles.cancelText}>Cancel</Text></Pressable></View></ScreenContainer>}
const styles=StyleSheet.create({card:{gap:14,padding:20,borderRadius:28,backgroundColor:'#0E1417',borderWidth:1,borderColor:'#FF5C7A44'},kicker:{color:'#FF5C7A',fontSize:11,fontWeight:'800',letterSpacing:1.5,textTransform:'uppercase'},title:{color:'#DDE3E7',fontSize:34,fontWeight:'300',letterSpacing:-1.4},body:{color:'#9BA6B2',lineHeight:22},input:{height:54,borderRadius:18,borderWidth:1,borderColor:'#3C494E',backgroundColor:'#1A2123',color:'#DDE3E7',paddingHorizontal:16},error:{color:'#FF5C7A',lineHeight:21},button:{height:52,borderRadius:26,alignItems:'center',justifyContent:'center',backgroundColor:'#FF5C7A'},buttonText:{color:'#2B0007',fontWeight:'900'},cancel:{height:44,alignItems:'center',justifyContent:'center'},cancelText:{color:'#9BA6B2',fontWeight:'800'}})
