import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { CanvasBackground } from '@/components/canvas/CanvasBackground';
import { usePhantm } from '@/lib/canvas-store';

const steps=[['Welcome to PHANTM','A phone-within-a-phone for notes, capture, browsing, voice, workflows, and focus.'],['This is your canvas.','Space is the launcher. Nests live at coordinates, not in tabs.'],['This is a nest.','A center node anchors orbital rings of slots.'],['Hold the center. Drag to explore.','Long-press the sun node, then move through the canvas.'],['Tap a ring slot.','Slots open modules as sheets while the canvas stays behind them.'],['Make it yours.','Every ring slot can be configured for modules, nest links, apps, or empty space.'],['Build your first nest.','Name your Main Nest and assign its first module.']];
export default function Onboarding(){const[step,setStep]=useState(0);const router=useRouter();const{completeOnboarding}=usePhantm();async function next(){if(step<steps.length-1)setStep(step+1);else{await completeOnboarding();router.replace('/setup')}}return <View style={styles.root}><CanvasBackground/><View style={styles.visual}><View style={styles.outer}/><View style={styles.inner}/><View style={styles.node}><View style={styles.core}/></View><MaterialIcons name={step<3?'blur-on':step<5?'gesture':'tune'} size={42} color="#39D5FF" style={styles.icon}/></View><View style={styles.copy}><Text style={styles.kicker}>Step {step+1} of {steps.length}</Text><Text style={styles.title}>{steps[step][0]}</Text><Text style={styles.body}>{steps[step][1]}</Text><Pressable onPress={next} style={({pressed})=>[styles.button,pressed&&styles.pressed]}><Text style={styles.buttonText}>{step===steps.length-1?'Build Main Nest':'Continue'}</Text></Pressable></View></View>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#05070A',padding:24,justifyContent:'space-between'},visual:{flex:1,alignItems:'center',justifyContent:'center'},outer:{position:'absolute',width:290,height:290,borderRadius:145,borderWidth:1,borderColor:'#86939822'},inner:{position:'absolute',width:168,height:168,borderRadius:84,borderWidth:1,borderColor:'#39D5FF33'},node:{width:36,height:36,borderRadius:18,backgroundColor:'#39D5FF',alignItems:'center',justifyContent:'center',shadowColor:'#39D5FF',shadowOpacity:.45,shadowRadius:24},core:{width:14,height:14,borderRadius:7,backgroundColor:'#003543'},icon:{position:'absolute',bottom:'28%'},copy:{paddingBottom:32,gap:14},kicker:{color:'#39D5FF',fontSize:11,fontWeight:'800',letterSpacing:1.5,textTransform:'uppercase'},title:{color:'#DDE3E7',fontSize:42,fontWeight:'300',letterSpacing:-2,lineHeight:46},body:{color:'#9BA6B2',fontSize:16,lineHeight:25},button:{height:54,borderRadius:27,backgroundColor:'#39D5FF',alignItems:'center',justifyContent:'center',marginTop:12},buttonText:{color:'#001F28',fontWeight:'900'},pressed:{opacity:.75,transform:[{scale:.98}]}})
