import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { ScreenContainer } from '@/components/screen-container';
import { usePhantm } from '@/lib/canvas-store';
import { exportNest, parseNestImport } from '@/lib/nest-utils';

export default function Settings(){const router=useRouter();const store=usePhantm();const[json,setJson]=useState('');const[status,setStatus]=useState('');function doExport(){if(store.activeNest)setJson(exportNest(store.activeNest))}function doImport(){const nest=parseNestImport(json);if(!nest){setStatus('That JSON does not look like a PHANTM nest.');return}store.importNest(nest);setStatus('Nest imported into the local canvas.')}return <ScreenContainer edges={['top','bottom','left','right']} className="p-5" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.back}><Text style={styles.backText}>Back</Text></Pressable><Text style={styles.title}>Settings</Text><Text style={styles.body}>Local-first preferences, JSON sharing, and reset controls for this PHANTM build.</Text></View><View style={styles.card}><Text style={styles.cardTitle}>Shareable Nest JSON</Text><Text style={styles.cardBody}>Export the active nest or paste an exported configuration to import it as a new local nest.</Text><TextInput value={json} onChangeText={setJson} multiline placeholder="Nest JSON" placeholderTextColor="#6B7880" style={styles.json}/><View style={styles.row}><Pressable onPress={doExport} style={styles.secondary}><Text style={styles.secondaryText}>Export Active</Text></Pressable><Pressable onPress={doImport} style={styles.primary}><Text style={styles.primaryText}>Import</Text></Pressable></View>{status?<Text style={styles.status}>{status}</Text>:null}</View><View style={styles.card}><Text style={styles.cardTitle}>Local Data</Text><Text style={styles.cardBody}>Reset onboarding, nests, captures, notes, voice metadata, and workflows stored on this device.</Text><Pressable onPress={async()=>{await store.resetAll();router.replace('/onboarding')}} style={styles.danger}><Text style={styles.dangerText}>Reset PHANTM</Text></Pressable></View></ScrollView></ScreenContainer>}
const styles=StyleSheet.create({content:{gap:16,paddingBottom:32},header:{gap:10},back:{alignSelf:'flex-start',height:40,paddingHorizontal:16,borderRadius:20,backgroundColor:'#1A2123',justifyContent:'center'},backText:{color:'#39D5FF',fontWeight:'800'},title:{color:'#DDE3E7',fontSize:38,fontWeight:'300',letterSpacing:-1.8},body:{color:'#9BA6B2',lineHeight:23},card:{padding:16,borderRadius:24,backgroundColor:'#0E1417',borderWidth:1,borderColor:'#2F3638',gap:12},cardTitle:{color:'#DDE3E7',fontSize:18,fontWeight:'800'},cardBody:{color:'#9BA6B2',lineHeight:21},json:{minHeight:130,borderRadius:18,borderWidth:1,borderColor:'#3C494E',backgroundColor:'#1A2123',color:'#DDE3E7',padding:12,textAlignVertical:'top'},row:{flexDirection:'row',gap:10},secondary:{flex:1,height:48,borderRadius:24,alignItems:'center',justifyContent:'center',backgroundColor:'#1A2123'},secondaryText:{color:'#DDE3E7',fontWeight:'800'},primary:{flex:1,height:48,borderRadius:24,alignItems:'center',justifyContent:'center',backgroundColor:'#39D5FF'},primaryText:{color:'#001F28',fontWeight:'900'},status:{color:'#39D5FF'},danger:{height:48,borderRadius:24,alignItems:'center',justifyContent:'center',backgroundColor:'#FF5C7A22',borderWidth:1,borderColor:'#FF5C7A55'},dangerText:{color:'#FF5C7A',fontWeight:'900'}})
