import { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { ScreenContainer } from '@/components/screen-container';
import { usePhantm } from '@/lib/canvas-store';
import { ContextMode, ModuleId, CONTEXT_COLORS, MODULE_LABELS } from '@/lib/phantm-types';

const modules:ModuleId[]=['notes','capture','timer','voice'];const contexts:ContextMode[]=['Neutral','Work','Personal','Focus','Travel'];
export default function Setup(){const router=useRouter();const{createMainNest}=usePhantm();const[label,setLabel]=useState('Main Nest');const[module,setModule]=useState<ModuleId>('notes');const[ctx,setCtx]=useState<ContextMode>('Neutral');async function finish(){await createMainNest(label,module,ctx);router.replace('/')}return <ScreenContainer edges={['top','bottom','left','right']} containerClassName="bg-background" className="p-6 justify-between"><View style={styles.top}><Text style={styles.kicker}>Main Nest Setup</Text><Text style={styles.title}>Let’s build your first nest.</Text><Text style={styles.body}>Name the anchor point for your canvas and assign at least one module slot before entering PHANTM.</Text><TextInput value={label} onChangeText={setLabel} placeholder="Main Nest" placeholderTextColor="#6B7880" style={styles.input}/><Text style={styles.section}>First Slot</Text><View style={styles.grid}>{modules.map(m=><Pressable key={m} onPress={()=>setModule(m)} style={[styles.choice,module===m&&{borderColor:'#39D5FF',backgroundColor:'#39D5FF18'}]}><Text style={styles.choiceText}>{MODULE_LABELS[m]}</Text></Pressable>)}</View><Text style={styles.section}>Context Accent</Text><View style={styles.grid}>{contexts.map(c=><Pressable key={c} onPress={()=>setCtx(c)} style={[styles.choice,ctx===c&&{borderColor:CONTEXT_COLORS[c],backgroundColor:`${CONTEXT_COLORS[c]}18`}]}><Text style={[styles.choiceText,{color:CONTEXT_COLORS[c]}]}>{c}</Text></Pressable>)}</View></View><Pressable onPress={finish} style={({pressed})=>[styles.button,{backgroundColor:CONTEXT_COLORS[ctx]},pressed&&styles.pressed]}><Text style={styles.buttonText}>Enter Canvas</Text></Pressable></ScreenContainer>}
const styles=StyleSheet.create({top:{gap:14},kicker:{color:'#39D5FF',fontSize:11,fontWeight:'800',letterSpacing:1.5,textTransform:'uppercase'},title:{color:'#DDE3E7',fontSize:38,fontWeight:'300',letterSpacing:-1.8,lineHeight:43},body:{color:'#9BA6B2',fontSize:16,lineHeight:24},input:{height:54,borderRadius:18,borderWidth:1,borderColor:'#3C494E',backgroundColor:'#1A2123',color:'#DDE3E7',fontSize:17,paddingHorizontal:16},section:{color:'#DDE3E7',fontWeight:'800',marginTop:10},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},choice:{minHeight:44,paddingHorizontal:14,borderRadius:22,borderWidth:1,borderColor:'#3C494E',backgroundColor:'#0E1417',alignItems:'center',justifyContent:'center'},choiceText:{color:'#DDE3E7',fontWeight:'800'},button:{height:56,borderRadius:28,alignItems:'center',justifyContent:'center'},buttonText:{color:'#001F28',fontWeight:'900'},pressed:{opacity:.75,transform:[{scale:.98}]}})
